# Generated by Django 5.0 on 2024-01-24 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appSites_2', '0005_rename_excert_aboutme_expert'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aboutme',
            old_name='desk',
            new_name='desc',
        ),
    ]
