# Generated by Django 5.0 on 2024-03-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Имя товара')),
                ('count', models.IntegerField(default=0, verbose_name='Кол-во товаров наскладе')),
                ('price', models.FloatField(default=0, verbose_name='Цена товаров')),
            ],
        ),
    ]
