# Generated by Django 5.0 on 2024-03-20 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appShop', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productshop',
            options={'verbose_name': 'товар', 'verbose_name_plural': 'товары'},
        ),
    ]
