# Generated by Django 5.0 on 2024-01-31 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название подкатегории')),
                ('gategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appKey.category', verbose_name='Категория')),
            ],
            options={
                'verbose_name': 'подкатегорию',
                'verbose_name_plural': 'подкатегорию',
            },
        ),
    ]
