# Generated by Django 5.0 on 2024-01-31 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0005_rename_gategory_subcategory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('RU', 'Рубль'), ('US', 'Доллар'), ('EU', 'Евро'), ('CHINA', 'Юань')], default='RU', max_length=10, verbose_name='Валюта'),
        ),
    ]
