# Generated by Django 5.0 on 2024-02-05 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appKey', '0007_alter_subcategory_options_photoproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PhotoProduct',
            new_name='PhotosProduct',
        ),
    ]
